steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-west2-docker.pkg.dev/portfolio-400613/nextjs-portfolio-docker/nextjs-docker-gcr-image:tag1",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west2-docker.pkg.dev/portfolio-400613/nextjs-portfolio-docker/nextjs-docker-gcr-image:tag1",
      ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "nextjs-docker-gcr-image"
      - "--image"
      - "us-west2-docker.pkg.dev/portfolio-400613/nextjs-portfolio-docker/nextjs-docker-gcr-image:tag1"
      - "--region"
      - "us-west2"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
images:
  - "us-west2-docker.pkg.dev/portfolio-400613/nextjs-portfolio-docker/nextjs-docker-gcr-image:tag1"